version: '2'

networks:
  default:
    external:
      name: illuminateeducation

services:
  app:
    image: tianon/true
    volumes:
      - $PWD:/var/www/service
        
  php:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    depends_on:
      - app
      - mongo
    volumes_from:
      - app

  nginx:
    image: nginx:alpine
    depends_on:
      - php
    volumes_from:
      - php
    volumes:
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
        
  mongo:
    image: mongo:latest
    command:
      - mongod 
      - --storageEngine
      - wiredTiger
        
  workspace:
    build:
      context: ./docker/workspace
      dockerfile: Dockerfile     
    volumes_from:
      - app
   
