version: '2'

networks:
  default:
    external:
      name: illuminateeducation

services:
  app:
    build:
      context: .
      args:
        - BUILD_ENV=production
    depends_on:
        - mongo
  nginx:
    image: nginx:alpine
    depends_on:
      - app
    volumes_from:
      - app
    volumes:
      - ./docker-fs/vhost.conf:/etc/nginx/conf.d/default.conf
  mongo:
    image: mongo:latest
