version: '2'

networks:
  default:
    external:
      name: illuminateeducation

services:
  app:
    image: tianon/true
    volumes:
      - $PWD:/var/www/service
        
  php:
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    depends_on:
      - mongo
    volumes_from:
      - app

  nginx:
    image: nginx:alpine
    depends_on:
      - php
    volumes_from:
      - php
    volumes:
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
        
  mongo:
    image: mongo:latest
