version: '2'
networks:
  default:
    external:
      name: illuminateeducation
services:
    php:
      build: .
      depends_on:
#        - db
        - redis_master
        - redis_slave
        - sentinel
#      environment:
#      working_dir: /var/www/service
#      volumes:
#        - ./:/var/www/service
    nginx:
      image: nginx:alpine
      depends_on:
        - php
      volumes_from:
        - php
      volumes:
        - ./docker-fs/vhost.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "80:80"
#    db:
#      image: postgres:alpine
#      environment:
#       - POSTGRES_PASSWORD=docker
#       - POSTGRES_USER=docker
    sentinel:
        image: s7anley/redis-sentinel-docker
        environment:
            - MASTER_NAME=mymaster
            - QUORUM=1
            - MASTER=redis_master
            - SLAVES=redis_slave
        depends_on:
            - redis_master
            - redis_slave
    redis_master:
        image: redis:alpine
    redis_slave:
        image: redis:alpine
