version: '2'
networks:
  default:
    external:
      name: illuminateeducation
services:
    php:
      build:
        context: ../
      depends_on:
        - mongo
    nginx:
      image: nginx:alpine
      depends_on:
        - php
      volumes_from:
        - php
      volumes:
        - ./docker-fs/vhost.conf:/etc/nginx/conf.d/default.conf
      ports:
         - "80:80"
    mongo:
      image: mongo:latest
